# Generated by Django 4.2 on 2024-08-11 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_name', models.CharField(max_length=30)),
                ('pizza_size', models.CharField(choices=[('M', 'Mediana'), ('X', 'XXL'), ('P', 'Personal'), ('F', 'Familiar')], max_length=10)),
                ('pizza_dough', models.CharField(choices=[('D', 'Delgada'), ('A', 'Artesanal'), ('T', 'Tradicional')], max_length=14)),
                ('ingredient_1', models.CharField(choices=[('P', 'Pepperoni'), ('QF', 'Queso Fontina'), ('CH', 'Chorizo'), ('PO', 'Pollo'), ('J', 'Jamon'), ('C', 'Choclo'), ('QP', 'Queso Parmesano'), ('SI', 'Salchica Italiana'), ('SA', 'Salchicha Alemana'), ('CA', 'Carne'), ('QM', 'Queso Mozzarela')], max_length=20)),
                ('ingredient_2', models.CharField(choices=[('P', 'Pepperoni'), ('QF', 'Queso Fontina'), ('CH', 'Chorizo'), ('PO', 'Pollo'), ('J', 'Jamon'), ('C', 'Choclo'), ('QP', 'Queso Parmesano'), ('SI', 'Salchica Italiana'), ('SA', 'Salchicha Alemana'), ('CA', 'Carne'), ('QM', 'Queso Mozzarela')], max_length=20)),
                ('ingredient_3', models.CharField(choices=[('P', 'Pepperoni'), ('QF', 'Queso Fontina'), ('CH', 'Chorizo'), ('PO', 'Pollo'), ('J', 'Jamon'), ('C', 'Choclo'), ('QP', 'Queso Parmesano'), ('SI', 'Salchica Italiana'), ('SA', 'Salchicha Alemana'), ('CA', 'Carne'), ('QM', 'Queso Mozzarela')], max_length=20)),
                ('ingredient_4', models.CharField(choices=[('P', 'Pepperoni'), ('QF', 'Queso Fontina'), ('CH', 'Chorizo'), ('PO', 'Pollo'), ('J', 'Jamon'), ('C', 'Choclo'), ('QP', 'Queso Parmesano'), ('SI', 'Salchica Italiana'), ('SA', 'Salchicha Alemana'), ('CA', 'Carne'), ('QM', 'Queso Mozzarela')], max_length=20)),
                ('description', models.CharField(max_length=150, null=True)),
                ('price_pizza', models.DecimalField(decimal_places=2, max_digits=10)),
                ('picture_pizza', models.ImageField(upload_to='picture_pizzas')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quito_pizza.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('price_product', models.DecimalField(decimal_places=2, max_digits=10)),
                ('picture_products', models.ImageField(upload_to='picture_products')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quito_pizza.category')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quito_pizza.client')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quito_pizza.pizza')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quito_pizza.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='quito_pizza.purchase')),
            ],
        ),
    ]
