# Generated by Django 4.2 on 2024-08-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quito_pizza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='ingredient_1',
            field=models.CharField(blank=True, choices=[('SA', 'Salchicha Alemana'), ('J', 'Jamon'), ('PO', 'Pollo'), ('P', 'Pepperoni'), ('CH', 'Chorizo'), ('CA', 'Carne'), ('-', '---'), ('SI', 'Salchica Italiana'), ('C', 'Choclo'), ('QM', 'Queso Mozzarela'), ('QF', 'Queso Fontina'), ('QP', 'Queso Parmesano')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='ingredient_2',
            field=models.CharField(blank=True, choices=[('SA', 'Salchicha Alemana'), ('J', 'Jamon'), ('PO', 'Pollo'), ('P', 'Pepperoni'), ('CH', 'Chorizo'), ('CA', 'Carne'), ('-', '---'), ('SI', 'Salchica Italiana'), ('C', 'Choclo'), ('QM', 'Queso Mozzarela'), ('QF', 'Queso Fontina'), ('QP', 'Queso Parmesano')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='ingredient_3',
            field=models.CharField(blank=True, choices=[('SA', 'Salchicha Alemana'), ('J', 'Jamon'), ('PO', 'Pollo'), ('P', 'Pepperoni'), ('CH', 'Chorizo'), ('CA', 'Carne'), ('-', '---'), ('SI', 'Salchica Italiana'), ('C', 'Choclo'), ('QM', 'Queso Mozzarela'), ('QF', 'Queso Fontina'), ('QP', 'Queso Parmesano')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='ingredient_4',
            field=models.CharField(blank=True, choices=[('SA', 'Salchicha Alemana'), ('J', 'Jamon'), ('PO', 'Pollo'), ('P', 'Pepperoni'), ('CH', 'Chorizo'), ('CA', 'Carne'), ('-', '---'), ('SI', 'Salchica Italiana'), ('C', 'Choclo'), ('QM', 'Queso Mozzarela'), ('QF', 'Queso Fontina'), ('QP', 'Queso Parmesano')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='pizza_dough',
            field=models.CharField(choices=[('T', 'Tradicional'), ('D', 'Delgada'), ('A', 'Artesanal')], max_length=14),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='pizza_size',
            field=models.CharField(choices=[('M', 'Mediana'), ('X', 'XXL'), ('F', 'Familiar'), ('P', 'Personal')], max_length=10),
        ),
    ]
